eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
server:
  port: 2929
spring:
  application:
   name: service-feign
feign:
  hystrix:
    enabled: true
