server:
  port: 8762

eureka:
  instance:
    hostname: master
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://backup1:8761/eureka/
