server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
 http:
  encoding:
    force: true
    charset: UTF-8
    enabled: true
 datasource:
     url: jdbc:mysql://localhost:3306/testdd?useUnicode=true&amp;characterEncoding=utf8
     username: root
     password: 123456
     driver-class-name: com.mysql.jdbc.Driver
     type: org.apache.commons.dbcp2.BasicDataSource
     dbcp2:
      initial-size: 50
      max-active: 250
      max-idle: 50
      min-idle: 5
      max-wait-millis: 10000
      validation-query: SELECT 1
      connection-properties: characterEncoding=utf8
 mvc:
  view:
   prefix: /WEB-INF/pages/
   suffix: .jsp
 redis:
  timeout: 0
  host: 127.0.0.1
  port: 6379
  pool:
   max-idle: 8
   max-active: 10
   max-wait: -1
   min-idle: 0
## Mybatis \u914D\u7F6E
mybatis:
 type-aliases-package: com.longhang.model
 mapper-locations: classpath:mapper/studentMapper.xml



